### ISSUE TITLE
How to get this JSON from Genotek?

### ISSUE THREAD

**Issue by Antiokh** [magicxor/GenotekToGedcom#1]
Tell me please, how did you got the Json? My Json which I can save from Dev Tools Network tab only shows close relatives.

**Comment by Antiokh** [comment]
It seems like they've secured the json, but I got it with Charles Proxy.

**Comment by magicxor** [comment]
It seems that the old method is still working. You may click "All" in the top right corner and retrieve the JSON file using Chrome dev tools.

![image](https://github.com/magicxor/GenotekToGedcom/assets/8275793/cc8d4c28-a48d-4a41-a632-6581f6e39522)

![image](https://github.com/magicxor/GenotekToGedcom/assets/8275793/458ddd9f-87d4-4c84-9273-fd42feb847fa)

**Comment by Antiokh** [comment]
> It seems that the old method is still working. You may click "All" in the top right corner and retrieve the JSON file using Chrome dev tools.
> 
> ![image](https://private-user-images.githubusercontent.com/8275793/285732199-cc8d4c28-a48d-4a41-a632-6581f6e39522.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyODExMTQsIm5iZiI6MTcwMTI4MDgxNCwicGF0aCI6Ii84Mjc1NzkzLzI4NTczMjE5OS1jYzhkNGMyOC1hNDhkLTRhNDEtYTYzMi02NTgxZjZlMzk1MjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjlUMTgwMDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjAwOGQxNWFkZDBmMDIxZjkyMzFmODlhMTBjZjMwNjU4NTVlNTg3NTQwNGQ3YjMyYTQ0OGMxZDFjMzBkZTAxZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Cdp9wjSmtPK0e55GqXsmHel0HwlN_FA68_y29m_HC00)
> 
> ![image](https://private-user-images.githubusercontent.com/8275793/285732384-458ddd9f-87d4-4c84-9273-fd42feb847fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyODExMTQsIm5iZiI6MTcwMTI4MDgxNCwicGF0aCI6Ii84Mjc1NzkzLzI4NTczMjM4NC00NThkZGQ5Zi04N2Q0LTRjODQtOTI3My1mZDQyZmViODQ3ZmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjlUMTgwMDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzY5MmI2MDZhYWU3OTU3MzI4Zjc0ZDIyNTgxM2ZkYmExOTkzNDhlM2NkMjM1M2U5MmQ2NGI3ZGMxMGY4ODVkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PApxPFcIgAVWXyd_kYguuG-r7EEpWoqW8cyVcdlLLek)

Doing exactly same way, but in dev tools I see mainly empty/nonsaved responses. I've used Charles Web Proxy to save the big json.
